# Site settings
title: Boston Displacement Mapping Project
email: antievictionboston@gmail.com
description: Stories and data to stop evictions for profit in Boston.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://antievictionboston.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:
social_image: /images/Maverick060.jpg

# Build settings
markdown: kramdown

# Defaults
defaults:
  - scope:
      type: maps
    values:
      layout: map

# Maps configuration
collections:
  maps:
    output: true
    permalink: /maps/:path/

# Bootstrap
sass:
  # loading path from site root
  # default to _sass
  load_paths: 
  - bower_components/bootstrap-sass/assets/stylesheets
  - _sass

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed    

